# -*- coding: utf-8 -*-
"""Small_Podcast_from_Notes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gHD9Bo6jBpNfdFdkuW1ifxryRoJFIQWa
"""

!pip install gradio openai -q

import gradio as gr
from openai import OpenAI
import tempfile

client = OpenAI(api_key="sk proj-9Bl12JnrNjSv5mJb9BccxvKGoMw0qmV-3GDxfLP73Xn77utG05iftqYKdX8Qiw_irrGtbmUQqTT3BlbkFJ6pTChisMd6Ktth6oBM_TPgZRb6stWgcwhnxTkjv_MSBVSYuiQRXId_Xa7svcUWIVpwu6qhxuIA")

def transform_to_podcast(notes: str) -> str:
    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {
                "role": "system",
                "content": (
                    "You are a friendly podcast host. "
                    "Transform the given notes into an engaging, "
                    "conversational podcast script. "
                    "Keep it clear, fun, and under 3 minutes when spoken."
                )
            },
            {
                "role": "user",
                "content": f"Transform these notes into a podcast script:\n\n{notes}"
            }
        ]
    )
    return response.choices[0].message.content

def text_to_speech(script: str) -> str:
    audio_response = client.audio.speech.create(
        model="tts-1",
        voice="alloy",
        input=script
    )
    temp_file = tempfile.NamedTemporaryFile(delete=False, suffix=".mp3")
    audio_response.stream_to_file(temp_file.name)
    return temp_file.name

def generate_podcast(notes: str):
    if not notes.strip():
        return "⚠️ Please enter some notes first!", None
    podcast_script = transform_to_podcast(notes)
    audio_path = text_to_speech(podcast_script)
    return podcast_script, audio_path

interface = gr.Interface(
    fn=generate_podcast,
    inputs=gr.Textbox(
        label="📝 Paste your notes here",
        placeholder="Write or paste your class notes here...",
        lines=10
    ),
    outputs=[
        gr.Textbox(label="🎙️ Generated Podcast Script", lines=10),
        gr.Audio(label="🔊 Your Podcast Audio")
    ],
    title="🎙️ Mini Podcast Generator",
    description="Paste your notes below and I will transform them into a podcast script and audio file!"
)

interface.launch()